# Generated by Django 5.1 on 2026-02-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('sector', models.CharField(choices=[('SERVICOS', 'Serviços'), ('COMERCIO', 'Comércio'), ('INDUSTRIA', 'Indústria')], max_length=20, verbose_name='Setor')),
                ('impact', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEUTRO', 'Neutro'), ('NEGATIVO', 'Negativo')], max_length=10, verbose_name='Classificação de Impacto')),
                ('suggestion_text', models.TextField(verbose_name='Texto da Sugestão')),
            ],
            options={
                'verbose_name': 'Matriz de Sugestão',
                'verbose_name_plural': 'Matrizes de Sugestões',
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Regra')),
                ('rule_type', models.CharField(choices=[('SIMPLES_NACIONAL', 'Simples Nacional'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('REFORMA', 'Pós-Reforma (IBS/CBS)')], max_length=20, verbose_name='Tipo de Regime/Regra')),
                ('sector', models.CharField(blank=True, choices=[('SERVICOS', 'Serviços'), ('COMERCIO', 'Comércio'), ('INDUSTRIA', 'Indústria')], max_length=20, null=True, verbose_name='Setor de Atuação')),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Alíquota (Ex: 0.1500)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Regra Tributária',
                'verbose_name_plural': 'Regras Tributárias',
            },
        ),
    ]
