# Generated by Django 5.2.11 on 2026-02-04 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_cnpj'),
        ('simulation', '0002_populate_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('monthly_revenue', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Faturamento Mensal')),
                ('costs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Custos')),
                ('tax_regime', models.CharField(choices=[('SIMPLES_NACIONAL', 'Simples Nacional'), ('LUCRO_PRESUMIDO', 'Lucro Presumido')], max_length=20, verbose_name='Regime Tributário')),
                ('sector', models.CharField(choices=[('SERVICOS', 'Serviços'), ('COMERCIO', 'Comércio'), ('INDUSTRIA', 'Indústria')], max_length=20, verbose_name='Setor de Atuação')),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF')),
                ('current_tax_load', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Carga Atual')),
                ('reform_tax_load', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Carga Reforma')),
                ('delta_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Diferença Absoluta')),
                ('impact_classification', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEUTRO', 'Neutro'), ('NEGATIVO', 'Negativo')], max_length=10, verbose_name='Classificação de Impacto')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Log de Simulação',
                'verbose_name_plural': 'Logs de Simulações',
                'ordering': ['-created_at'],
            },
        ),
    ]
