# Generated by Django 5.2.11 on 2026-02-04 21:49

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Formato: 00.000.000/0000-00 ou apenas números.', max_length=18, null=True, unique=True, validators=[core.validators.validate_cnpj], verbose_name='CNPJ'),
        ),
    ]
