# Generated by Django 5.2.11 on 2026-02-04 22:44

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(help_text='Formato: 00.000.000/0000-00 ou apenas números.', max_length=18, unique=True, validators=[core.validators.validate_cnpj], verbose_name='CNPJ'),
        ),
    ]
